language: minimal
dist: bionic
sudo: false

services:
  - docker

install:
  - docker-compose run --rm shards

before_script:
  - docker-compose run --rm check

script:
  - docker-compose run --rm spec
